name: Deploy MultiDocker
on:
  push:
    branches:
      - master # check your repo, your default branch might be master!

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t AKV-20/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true AKV-20/react-test npm test

      - run: docker build -t AKV-20/multi-client ./client
      - run: docker build -t AKV-20/multi-nginx ./nginx
      - run: docker build -t AKV-20/multi-server ./server
      - run: docker build -t AKV-20/multi-worker ./worker

      - run: docker push AKV-20/multi-client
      - run: docker push AKV-20/multi-nginx
      - run: docker push AKV-20/multi-server
      - run: docker push AKV-20/multi-worker
